export * from './types.js';
import type { AdjacencyYield, Axial, Board, Cargo, Civilization, GreatWork, PlayerId, PlayerState, ResourceStock, SeasonClock, SessionAction, SessionState, SessionView, Tile, TileId, Resource, Infrastructure, Structure, Season, AssemblyPolicy } from './types.js';

export const RESOURCES: readonly Resource[];
export function resources(values?: Cargo): ResourceStock;
export function resourceTotal(amount: ResourceStock): number;
export function addResources(stock: ResourceStock, amount: ResourceStock): ResourceStock;
export function spendResources(stock: ResourceStock, amount: ResourceStock): ResourceStock;
export const HEX_DIRECTIONS: readonly (readonly [number, number])[];
export function hexKey(q: number, r: number): TileId;
export function hexDistance(a: Axial, b: Axial): number;
export function adjacentTiles(board: Board, tileId: TileId): Tile[];
export function createBoard(radius?: number): Board;
export function calculateTileYield(board: Board, tileId: TileId, civilization: Civilization, round?: number): AdjacencyYield;
export function calculatePlayerYield(board: Board, player: PlayerState, round: number): { yield: ResourceStock; impact: number };
export const STRUCTURES: Readonly<Record<Structure, { cost: Cargo; terrains: string[]; yield: Cargo; terrainBonus: string[]; partnerBonus: Structure[]; impact: number }>>;
export const CIVILIZATIONS: Readonly<Record<Civilization, { name: string; multipliers: ResourceStock; biome: string }>>;
export const INFRASTRUCTURE: Readonly<Record<Infrastructure, { cost: Cargo; capacity: number; terrains: string[] }>>;
export function edgeKey(a: TileId, b: TileId): string;
export function findRoute(board: Board, from: TileId, to: TileId, actorId: PlayerId, round: number, usage?: Record<string, number>, cargoSize?: number): TileId[] | null;
export function reserveRoute(board: Board, usage: Record<string, number>, path: TileId[], from: TileId, to: TileId, cargo: Cargo, actorId: PlayerId, round: number): Record<string, number>;
export const GREAT_WORK_STAGES: readonly { id: string; name: string; cost: Cargo; deadline: number }[];
export function createGreatWork(site?: TileId): GreatWork;
export function contributeGreatWork(previous: GreatWork, playerId: PlayerId, cargo: Cargo, round: number): GreatWork;
export function greatWorkMissedDeadline(work: GreatWork, round: number): boolean;
export function greatWorkContributors(work: GreatWork): PlayerId[];
export const SEASONS: readonly Season[];
export const SESSION_RULES: Readonly<{ rounds: number; roundsPerSeason: number; actions: number; minimumBalance: number }>;
export const ASSEMBLY_POLICIES: Readonly<Record<AssemblyPolicy, { balance: number; actions: number }>>;
export function seasonClock(round: number): SeasonClock;
export function createSession(roster?: { id: PlayerId; civilization: Civilization }[]): SessionState;
export function applySessionAction(previous: SessionState, action: SessionAction): SessionState;
export function sessionView(state: SessionState, playerId: PlayerId): SessionView;
